; Walpa - Lossless Icon Coloring Software
; Walpa - Chinese Lang File.
; (C) Copyright 2026, Eray Türkay.
; Publisher: Türkaysoft
; Project Type: Open Source
; License: MIT License
; Website: https://turkaysoft.com
; GitHub: https://github.com/turkaysoft/walpa

[Main]
lang_name = Chinese / China
lang_tag = zh
translator = TS Translator Team
walpa_version = v26.8

[HeaderMenu]
header_menu_settings = 设置
header_menu_theme = 主题
header_menu_language = 语言 (Language)
header_menu_start = 启动
header_menu_listview = 列表视图
header_menu_update = 检查更新
header_menu_donate = 捐赠
header_menu_about = 关于

[HeaderThemes]
theme_light = 浅色主题
theme_dark = 深色主题
theme_system = 系统主题

[HeaderLangs]
lang_ar = 阿拉伯语 (Arabic)
lang_zh = 中文 (Chinese)
lang_en = 英语 (English)
lang_nl = 荷兰语 (Dutch)
lang_fr = 法语 (French)
lang_de = 德语 (German)
lang_hi = 印地语 (Hindi)
lang_it = 意大利语 (Italian)
lang_ja = 日语 (Japanese)
lang_ko = 韩语 (Korean)
lang_pl = 波兰语 (Polish)
lang_pt = 葡萄牙语 (Portuguese)
lang_ru = 俄语 (Russian)
lang_es = 西班牙语 (Spanish)
lang_tr = 土耳其语 (Turkish)

[LangChange]
lang_change_notification = 语言已更改. {0}某些字段需要重新启动程序以应用更改. {1}是否现在重新启动程序？

[HeaderViewMode]
header_view_mode_windowed = 窗口模式
header_view_mode_full_screen = 全屏模式

[HeaderListViewMode]
header_list_view_mode_file_name = 文件名
header_list_view_mode_full_path = 文件路径

[HeaderHelp]
header_help_info_notification = {0} 已经打开. 

[WalpaMain]
wm_label_pb_before = 原始图标：
wm_label_pb_after = 新图标：
wm_btn_clear_list = 清空列表
wm_btn_file_select = 选择图标
wm_btn_color_select = 选择颜色
wm_btn_save_location_select = 保存位置
wm_btn_convert = 转换
wm_filter_image = 图标文件 {0}
wm_filter_title = {0} - 请选择有效的图标. 
wm_filter_save_tag = 请选择保存转换后图片的文件夹. 
wm_label_save_location = 保存位置：
wm_label_save_location_null = 尚未设置. 
wm_icon_count_title = 图标数量：
wm_icon_not_yet = 尚未导入. 
wm_icon_count = {0} 个图标已准备好转换. {1}总大小：{2}
wm_label_select_color = 已选颜色：
wm_warning_list_zero = 请将要转换的图标添加到列表中. 
wm_warning_color = 在开始转换过程之前，请选择一种颜色. 
wm_warning_save_directory = 在开始转换过程之前，请指定一个保存文件夹. 
wm_process_query = 您确定要开始转换过程吗?
wm_process_running = {0} - {1} 正在转换 ({2}/{3})
wm_success_convert = {0} 个图标已成功转换并保存到 '{1}'. {2}您现在要查看它们吗?
wm_failed_convert = 转换完成，但某些文件出现问题. {0}成功：({1}/{2}) 个文件. 

[WalpaColorPicker]
wcp_title = {0} - 颜色选择器
wcp_label_premade = 预设颜色
wcp_label_color_picker = 颜色选择器
wcp_label_manual = 手动调整
wcp_label_preview = 预览
wcp_button_select = 选择
wcp_alert_select = 请选择一种颜色，然后重试. 

; SOFTWARE UPDATE
; ====================================================================

[SoftwareUpdate]
su_title = {0} - 更新检查器
su_available = {0} 有新版本可用！{1}您当前版本：v{2}{3}最新版本：v{4}{5}按“是”启动 TS 更新向导并下载新版本. 
su_not_available = {0} 已是最新版本. {1}客户端版本：v{2}
su_newer = 恭喜！{0}您是最早体验版本 {1} 的用户之一，该版本尚未正式发布！
su_ts_updater_c_running = TS 更新向导正在运行. 应用程序即将关闭...
su_ts_updater_not_available = 未找到 {0} 文件. 正在重定向到 GitHub 下载页面...
su_not_connection = 由于无法建立互联网连接，无法完成更新检查. {0}请检查您的网络连接后重试. 
su_error = 检查更新时发生错误. 请稍后再试. {0}错误：{1}

; TS UPDATER
; ====================================================================

[TSUpdater]
tsu_title = {0} - 更新向导 {1} - {2}
tsu_subtitle = TS - 更新向导
tsu_ui_loading = 正在加载...
tsu_ui_release_notes = 发布说明
tsu_version_not_installed = 当前：未安装
tsu_app_default_name = 应用程序
tsu_status_checking = 正在检查...
tsu_status_ready_update = 可进行更新或安装. 
tsu_status_ready_launch = 已准备好启动应用程序. 
tsu_status_downloading = 正在下载...
tsu_status_extracting = 正在解压文件...
tsu_status_launching = 正在启动应用程序...
tsu_status_error = 发生错误，请重试. 
tsu_status_preparing = 正在准备...
tsu_button_preparing = 正在准备...
tsu_button_launching = 正在启动...
tsu_button_retry = 重试
tsu_button_start_update = 开始更新
tsu_button_start_install = 开始安装
tsu_button_start_app = 启动应用程序
tsu_button_start = 开始
tsu_substatus_checking_versions = 正在检查应用程序版本...
tsu_substatus_download_starting = 正在开始下载...
tsu_substatus_extracting_files = 正在解压文件...
tsu_substatus_preparing_app = 正在准备启动应用程序...
tsu_substatus_please_wait = 请稍候...
tsu_status_new_version_available = {0} 有新版本可用！
tsu_status_ready_for_install = {0} 已准备好安装. 
tsu_status_app_up_to_date = {0} 已是最新版本. 
tsu_status_connecting_to_server = 正在连接服务器...
tsu_error_url_message = 无法生成更新链接，请检查设置. 
tsu_error_timeout_message = 服务器响应超时，请检查网络连接后重试. 
tsu_error_connection_message = 服务器连接错误：
tsu_error_version_check_message = 版本检查错误：
tsu_error_download_url_message = 下载链接未配置或无法生成. 
tsu_error_invalid_download_url = 下载链接为空或无效. 
tsu_error_config_load = 无法加载应用程序配置. 
tsu_error_on_startup = 启动应用程序时发生错误：
tsu_error_release_page_not_configured = 未配置发布说明页面链接. 
tsu_error_open_release_page = 无法打开发布说明页面：
tsu_error_download_message = 下载过程中发生错误：
tsu_error_zip_not_found = 未找到 ZIP 文件. 请点击按钮重试. 
tsu_error_extraction_failed = 安装无法完成. 请点击按钮重试. 
tsu_error_invalid_file_path = 检测到无效文件路径 (已阻止 Zip Slip). 
tsu_error_self_exe_update = 自身程序更新错误：
tsu_error_extraction_files = 解压文件时发生错误：
tsu_error_during_operation = 操作过程中发生错误：
tsu_error_launch_app = 无法启动应用程序：
tsu_error_launch_exception = 启动应用程序时发生错误：
tsu_app_will_exit = 程序将退出. 
tsu_ask_view_release_notes = 是否要查看为 {0} 发布的发行说明？{1}发行说明可能包含需要注意的重要更改和信息. 
tsu_confirm_new_version = {0} 有新版本可用. {1}是否下载并安装新版本? 
tsu_confirm_install = 将下载并安装 {0}. {1}是否继续? 
tsu_success_update_completed = {0} 已成功更新. 
tsu_success_install_completed = {0} 已成功安装. 
tsu_prompt_launch_after_update = {0} 更新已完成. 是否立即启动应用程序? 
tsu_prompt_launch_app = 是否立即启动 {0}? 
tsu_prompt_launch_after_install = {0} 安装已完成. 是否立即启动应用程序? 
tsu_current_version_label = 当前：{0}
tsu_exe_not_found = 未找到可执行文件 (.exe)，请检查文件路径. 
tsu_error_file_in_use = {0} 当前正在运行. 请在更新前关闭正在运行的程序. 
tsu_online_version_label = 最新：{0}
tsu_zip_not_found_error = 未找到 ZIP 文件. 
tsu_download_completed_label = 已下载
tsu_file_label = 文件：

; ABOUT
; ====================================================================

[SoftwareAbout]
sa_title = {0} - 关于
sa_website_link = 网站
sa_github_link = GitHub
sa_donate_link = 捐赠
sa_lang_name = 语言
sa_lang_translator = 翻译员